#!/bin/bash

decalre -a random

for ((i = 0; i < 20; i++)); do

	random[$i]=$((RANDOM % 30))
	
done

echo "Random numbers are: "

sleep 1

echo "Calculating..." 

sleep 1

for num in "${random[@]}"; do
	
	echo "$num"
	
done
