#!/bin/bash

echo "Enter two numbers to see who's larger: "

read num1

read num2

if [[ $num1 -gt $num2 ]]; then

echo "calculating..."

sleep 1

echo "$num1 is really is greater"

else

echo "calculating..."

sleep 1

echo "$num2 is the real og"

fi

